### ISSUE TITLE
Doctest expression result is nil 

### ISSUE THREAD

**Issue by samuelmanzanera** [angelikatyborska/doctest_formatter#12]
Hello

Thanks for you project, this awesome.
I wanted to try it on a big project, where doctest sometimes are well indented.
However I got an error when I tried to run it

```
* (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
    (elixir 1.14.1) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.14.1) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.14.1) lib/enum.ex:4307: Enum.join/2
    lib/doctest_formatter/formatter.ex:107: DoctestFormatter.Formatter.format_result/2
    lib/doctest_formatter/formatter.ex:73: DoctestFormatter.Formatter.do_format_expression/2
    (elixir 1.14.1) lib/enum.ex:4249: Enum.flat_map_list/2
    (elixir 1.14.1) lib/enum.ex:4250: Enum.flat_map_list/2
    lib/doctest_formatter/formatter.ex:63: DoctestFormatter.Formatter.format_doc_content/2
```

It turns out not the struct `%DoctestFormatter.DoctestExpression` has the `result` field as `nil`. My guess is the initial doctests are not well indented, but I would expect this formatter to support that case.

I'm using Elixir 1.14.1 / OTP 25

**Comment by angelikatyborska** [comment]
Hi! Thank you for the bug report.

I think I found the problem. It's about doctests without any expected results, like this:

```
  @doc """
  iex> 2 + 3
  """
```

I can't believe I forgot to test this case 😁 

I'll try to fix it in the next 2 days and release `0.2.1`.

**Comment by angelikatyborska** [comment]
@samuelmanzanera I released version 0.2.1 to hex. That should fix the bug you were experiencing. Please let me know if it did, and if there are any other bugs 🙏
